### ISSUE TITLE
Normalize storage event

### ISSUE THREAD

**Issue by planttheidea** [ripeworks/local-storage-fallback#6]
Love the package! The normalization it tries to do for browser storage is awesome, except I noticed that it does not provide the same normalization for the storage change events.

For `localStorage` / `sessionStorage`, the spec includes a standard `storage` event that notifies of the change (https://developer.mozilla.org/en-US/docs/Web/Events/storage), and there is a similar fallback for cookies (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/cookies/onChanged). It would be pretty sweet if we could normalize that to a standard event that you could listen to on the imported object, something like

```javascript
import storage from 'local-storage-fallback';

storage.on('change', () => {...});
```

This would facilitate cross-tab communication more in line with the `localStorage` spec, even if cookies are used. What do you think?

**Comment by tamagokun** [comment]
Ah, thanks for this! I actually had no idea there were storage events. I'd love to get this in there.

**Comment by tamagokun** [comment]
I've been able to read up on the docs for this. It's starting to make more sense.

So, `localStorage` and `sessionStorage` don't actually emit the event, it's emitted from `window`. So when you are attaching your listener, you'd generally do it on window: i.e.

```js
window.addEventListener('storage', () => {...});
```

So, to normalize, I could have the `setItem` and `removeItem` in `CookieStorage` just emit a `storage` event on window, with a stubbed `StorageEvent` object.

Would that work?

I wouldn't really want to use `cookies.onChanged` since it's only a part of the web extensions API.

**Comment by planttheidea** [comment]
So the only thing is that any stubbed event on the window would operate solely within the same tab... The storage event is rippled across all tabs, allowing them to sync. I brought up the cookies onChange because it appeared to do the same, but if the same tab only thing is an okay limitation then to worries (it already would have been for the memory fallback).

**Comment by tamagokun** [comment]
Ah, I see. Yeah, that kind of stinks then.

I'd prefer to keep the native localStorage and sessionStorage objects when supported rather than creating an `on` method or extending them from `EventEmitter`.

Could it work like this?

```js
class CookieStorage {
  constructor () {
    browser.cookies.onChanged.addListener(function () {
      window.dispatchEvent(new StorageEvent('storage', {
        key: '', oldValue: '', newValue: ''
      }));
    });
  }
}
```

The idea here is that each instance in each tab would listen to the event, and dispatch `StorageEvent` to its own window. That way it's _normalized_ to the spec and you could listen across tabs (I think).

Of course, there would probably be some code in there to detect the cookie change and determine if the change was part of that storage instance using the `prefix` to do key checking.

**Comment by planttheidea** [comment]
Yup, I think that would work. Logically if cookie storage was used the storage event would not exist, so you're not trampling over native events.

**Comment by dfdeagle47** [comment]
A side note if anyone is looking to implement this: normally, the "storage" event is only fired in tabs that did not initiate the change.

However, on IE11, the "storage" event is fired on all tabs (even the one that triggered the change).

If the storage event is normalized, we'd have to decide whether we want to keep the IE11 behavior for all storage fallbacks, or fix this issue as well. Personally, I'd fix it to normalize the behavior across all browsers.
